package com.t1.db.t1_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE FornitoreBaseDto PLEASE EDIT ../FornitoreDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Fornitore object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.t1.db.t1_db.entity.Fornitore;
// Import relations
import com.t1.db.t1_db.dtos.infos.RisorsaInfo;



public class FornitoreBaseDto {
	
	private Long _id;
	
	// Attributes
    private String descrizione;
	
	// Relations Risorsa
	private List<Long> fornitore_Risorsa = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
    
	// Relations Risorsa
	
	public List<Long> getfornitore_Risorsa() {
		return this.fornitore_Risorsa;
	}

    public void setfornitore_Risorsa(List<RisorsaInfo> list) {
		this.fornitore_Risorsa = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	

    
}