package com.t1.db.t1_db.repositories.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE RisorsaBaseRepository PLEASE EDIT ../RisorsaRepository.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import java.util.List;
import com.t1.db.t1_db.entity.Risorsa;

import com.t1.db.t1_db.entity.Fornitore;

import com.t1.db.t1_db.entity.Tecnologia;


@Repository
public interface RisorsaBaseRepository extends CrudRepository<Risorsa, Long> {
    
    List<Risorsa> findByFornitore(Fornitore fornitore);
    
    
    
    
    List<Risorsa> findByTecnologie(Tecnologia tecnologia);
    
}